#########################################
# spring profiles configuration
#########################################
spring:
  profiles:
#    active: @env@
    active: dev
#    active: test
#    active: prod

#########################################
# spp configuration
#########################################

spp:
  #########################################
  # crawlers configuration
  #########################################
  crawlers:
    - key: htmlCrawler1
      enable: true
      name: html示例爬虫1
      baseUrl: http://www.example.com
      pages: 1
      pageNoDict: "{1:\"b97827cc\", 2:\"f8a0e15f\"}"
      type: HTML
      rowsParser: data
      rowsSelector: div.table-responsive table tbody tr
      cellSelector: td
      headRowIndex: 0
      ipIndex: 0
      ipValueParser: com.spp.core.strategy.DefaultParser
      portIndex: 1
      portValueParser: com.spp.core.strategy.DefaultParser
      cityIndex: 2
      cityNameParser: com.spp.core.strategy.DefaultParser
      expireUnit: MINUTE
      expireOffset: 10
      lock: false
    - key: jsonCrawler1
      enable: true
      name: json示例爬虫1
      baseUrl: http://www.example.com
      type: JSON
      rowsParser: data
      cityNameParser: com.spp.core.strategy.DefaultParser
      expireUnit: MINUTE
      expireOffset: 10
      lock: false

