#########################################
# spring profiles configuration
#########################################
spring:
  profiles:
#    active: @env@
    active: dev
#    active: test
#    active: prod
